export const mockAnalytics = {
  totalFarmers: 1250,
  totalFisherfolks: 847,
  totalRegistered: 2097,
  percentageFarmers: 59.6,
  percentageFisherfolks: 40.4,
  activeMembers: 1680,
  inactiveMembers: 417,
  percentageActive: 80.1,
  percentageInactive: 19.9,
}

const baseRecordFields = {
  lastName: '',
  firstName: '',
  middleName: '',
  extName: '',
  birthdate: '',
  age: '',
  gender: '',
  civilStatus: '',
  designation: '',
  unaKard: '',
  imc: '',
  uMobileAccount: '',
  lguCodeNo: '',
  ffrsSystemGeneratedNo: '',
  ffrsDateEncoded: '',
  fishrNo: '',
  contactNo: '',
  association: '',
  familyMembers: '',
  organic: '',
  fourPsMember: '',
  ipsMember: '',
  severelyStuntedChildren: '',
  motherMaidenName: '',
  householdHead: '',
  householdHeadSpecify: '',
  typeOfId: '',
  idNo: '',
  farmerFisherfolkBoth: '',
  farmType: '',
  cropAreaOrHeads: '',
  cropName: '',
  remarks: '',
}

const rawRecords = [
  {
    id: 1,
    name: 'Juan Dela Cruz',
    type: 'Farmer',
    barangay: 'Barangay 1',
    contactNumber: '09171234567',
    cropType: 'Rice',
    yearsExperience: 15,
    createdAt: '2026-01-15',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Maria Santos',
    type: 'Fisherfolk',
    barangay: 'Barangay 2',
    contactNumber: '09171234568',
    cropType: 'Bangus',
    yearsExperience: 10,
    createdAt: '2026-01-16',
    status: 'Inactive',
  },
  {
    id: 3,
    name: 'Pedro Reyes',
    type: 'Farmer',
    barangay: 'Barangay 3',
    contactNumber: '09171234569',
    cropType: 'Corn',
    yearsExperience: 8,
    createdAt: '2026-01-17',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Rosa Fernandez',
    type: 'Fisherfolk',
    barangay: 'Barangay 1',
    contactNumber: '09171234570',
    cropType: 'Tilapia',
    yearsExperience: 12,
    createdAt: '2026-01-18',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Antonio Morales',
    type: 'Farmer',
    barangay: 'Barangay 4',
    contactNumber: '09171234571',
    cropType: 'Vegetables',
    yearsExperience: 6,
    createdAt: '2026-01-19',
    status: 'Inactive',
  },
  // Additional mock records
  { id: 6, name: 'Luz Navarro', type: 'Fisherfolk', barangay: 'Barangay 5', contactNumber: '09171234572', cropType: 'Crab', yearsExperience: 7, createdAt: '2026-01-20', status: 'Active' },
  { id: 7, name: 'Mario Cruz', type: 'Farmer', barangay: 'Barangay 2', contactNumber: '09171234573', cropType: 'Rice', yearsExperience: 4, createdAt: '2026-01-20', status: 'Active' },
  { id: 8, name: 'Elena Ramos', type: 'Fisherfolk', barangay: 'Barangay 6', contactNumber: '09171234574', cropType: 'Shrimp', yearsExperience: 5, createdAt: '2026-01-21', status: 'Inactive' },
  { id: 9, name: 'Ramon Diaz', type: 'Farmer', barangay: 'Barangay 7', contactNumber: '09171234575', cropType: 'Corn', yearsExperience: 9, createdAt: '2026-01-21', status: 'Active' },
  { id: 10, name: 'Eva Bautista', type: 'Fisherfolk', barangay: 'Barangay 3', contactNumber: '09171234576', cropType: 'Bangus', yearsExperience: 11, createdAt: '2026-01-22', status: 'Active' },
  { id: 11, name: 'Josefina Cruz', type: 'Farmer', barangay: 'Barangay 8', contactNumber: '09171234577', cropType: 'Vegetables', yearsExperience: 2, createdAt: '2026-01-22', status: 'Inactive' },
  { id: 12, name: 'Noel Garcia', type: 'Farmer', barangay: 'Barangay 9', contactNumber: '09171234578', cropType: 'Rice', yearsExperience: 14, createdAt: '2026-01-23', status: 'Active' },
  { id: 13, name: 'Carla Santos', type: 'Fisherfolk', barangay: 'Barangay 10', contactNumber: '09171234579', cropType: 'Tilapia', yearsExperience: 3, createdAt: '2026-01-23', status: 'Inactive' },
  { id: 14, name: 'Vicente Lopez', type: 'Farmer', barangay: 'Barangay 11', contactNumber: '09171234580', cropType: 'Corn', yearsExperience: 6, createdAt: '2026-01-24', status: 'Active' },
  { id: 15, name: 'Grace Ramos', type: 'Fisherfolk', barangay: 'Barangay 12', contactNumber: '09171234581', cropType: 'Shrimp', yearsExperience: 8, createdAt: '2026-01-24', status: 'Active' },
  { id: 16, name: 'Leandro Pineda', type: 'Farmer', barangay: 'Barangay 1', contactNumber: '09171234582', cropType: 'Rice', yearsExperience: 5, createdAt: '2026-01-25', status: 'Inactive' },
  { id: 17, name: 'Nina Alvarez', type: 'Fisherfolk', barangay: 'Barangay 4', contactNumber: '09171234583', cropType: 'Bangus', yearsExperience: 10, createdAt: '2026-01-25', status: 'Active' },
  { id: 18, name: 'Arturo Mendoza', type: 'Farmer', barangay: 'Barangay 6', contactNumber: '09171234584', cropType: 'Vegetables', yearsExperience: 7, createdAt: '2026-01-26', status: 'Active' },
  { id: 19, name: 'Belen Flores', type: 'Fisherfolk', barangay: 'Barangay 7', contactNumber: '09171234585', cropType: 'Tilapia', yearsExperience: 4, createdAt: '2026-01-26', status: 'Inactive' },
  { id: 20, name: 'Oscar Reyes', type: 'Farmer', barangay: 'Barangay 8', contactNumber: '09171234586', cropType: 'Corn', yearsExperience: 12, createdAt: '2026-01-27', status: 'Active' },
  { id: 21, name: 'Pia Gutierrez', type: 'Fisherfolk', barangay: 'Barangay 9', contactNumber: '09171234587', cropType: 'Crab', yearsExperience: 6, createdAt: '2026-01-27', status: 'Active' },
  { id: 22, name: 'Rolando Santos', type: 'Farmer', barangay: 'Barangay 10', contactNumber: '09171234588', cropType: 'Rice', yearsExperience: 9, createdAt: '2026-01-28', status: 'Inactive' },
  { id: 23, name: 'Sandra Dizon', type: 'Fisherfolk', barangay: 'Barangay 11', contactNumber: '09171234589', cropType: 'Shrimp', yearsExperience: 3, createdAt: '2026-01-28', status: 'Active' },
  { id: 24, name: 'Tomas Aquino', type: 'Farmer', barangay: 'Barangay 12', contactNumber: '09171234590', cropType: 'Vegetables', yearsExperience: 1, createdAt: '2026-01-29', status: 'Inactive' },
  { id: 25, name: 'Ursula Navarro', type: 'Fisherfolk', barangay: 'Barangay 5', contactNumber: '09171234591', cropType: 'Bangus', yearsExperience: 11, createdAt: '2026-01-29', status: 'Active' },
  { id: 26, name: 'Waldo Castillo', type: 'Farmer', barangay: 'Barangay 2', contactNumber: '09171234592', cropType: 'Corn', yearsExperience: 13, createdAt: '2026-01-30', status: 'Active' },
  { id: 27, name: 'Yolanda Cruz', type: 'Fisherfolk', barangay: 'Barangay 3', contactNumber: '09171234593', cropType: 'Tilapia', yearsExperience: 5, createdAt: '2026-01-30', status: 'Inactive' },
  { id: 28, name: 'Zandro Villanueva', type: 'Farmer', barangay: 'Barangay 4', contactNumber: '09171234594', cropType: 'Rice', yearsExperience: 3, createdAt: '2026-01-31', status: 'Active' },
  { id: 29, name: 'Alicia Lim', type: 'Fisherfolk', barangay: 'Barangay 6', contactNumber: '09171234595', cropType: 'Crab', yearsExperience: 9, createdAt: '2026-01-31', status: 'Active' },
  { id: 30, name: 'Benito Ong', type: 'Farmer', barangay: 'Barangay 7', contactNumber: '09171234596', cropType: 'Vegetables', yearsExperience: 4, createdAt: '2026-02-01', status: 'Inactive' },
  { id: 31, name: 'Carmen Uy', type: 'Fisherfolk', barangay: 'Barangay 8', contactNumber: '09171234597', cropType: 'Shrimp', yearsExperience: 7, createdAt: '2026-02-01', status: 'Active' },
  { id: 32, name: 'Diego Tan', type: 'Farmer', barangay: 'Barangay 9', contactNumber: '09171234598', cropType: 'Corn', yearsExperience: 6, createdAt: '2026-02-02', status: 'Active' },
  { id: 33, name: 'Estela Chua', type: 'Fisherfolk', barangay: 'Barangay 10', contactNumber: '09171234599', cropType: 'Tilapia', yearsExperience: 2, createdAt: '2026-02-02', status: 'Inactive' },
  { id: 34, name: 'Federico Lao', type: 'Farmer', barangay: 'Barangay 11', contactNumber: '09171234600', cropType: 'Rice', yearsExperience: 8, createdAt: '2026-02-03', status: 'Active' },
  { id: 35, name: 'Gloria Sy', type: 'Fisherfolk', barangay: 'Barangay 12', contactNumber: '09171234601', cropType: 'Bangus', yearsExperience: 10, createdAt: '2026-02-03', status: 'Inactive' },
]

export const mockRecords = rawRecords.map((record, index) => {
  const nameParts = record.name.split(' ')
  const firstName = nameParts[0] ?? ''
  const lastName = nameParts[nameParts.length - 1] ?? ''
  const middleName = nameParts.length > 2 ? nameParts.slice(1, -1).join(' ') : ''
  const age = 18 + (record.id % 30)
  const birthYear = 2026 - age

  return {
    ...baseRecordFields,
    ...record,
    firstName,
    lastName,
    middleName,
    birthdate: `${birthYear}-01-15`,
    age: String(age),
    gender: index % 2 === 0 ? 'Male' : 'Female',
    civilStatus: index % 3 === 0 ? 'Married' : 'Single',
    designation: record.type === 'Farmer' ? 'Farmer' : 'Fisherfolk',
    contactNo: record.contactNumber,
    association: index % 4 === 0 ? 'Farmers Association' : 'Fisherfolk Union',
    familyMembers: String(3 + (record.id % 5)),
    organic: index % 2 === 0 ? 'Yes' : 'No',
    fourPsMember: index % 4 === 0 ? 'Yes' : 'No',
    ipsMember: index % 5 === 0 ? 'Yes' : 'No',
    severelyStuntedChildren: String(record.id % 3 === 0 ? 1 : 0),
    motherMaidenName: index % 2 === 0 ? 'Santos' : 'Reyes',
    householdHead: index % 2 === 0 ? 'Yes' : 'No',
    householdHeadSpecify: index % 2 === 0 ? '' : 'Spouse',
    typeOfId: 'National ID',
    idNo: `ID-${String(record.id).padStart(4, '0')}`,
    farmerFisherfolkBoth: record.type,
    farmType: record.type === 'Farmer' ? 'Crop' : 'Fishery',
    cropAreaOrHeads: record.type === 'Farmer' ? '2.5 ha' : '120 heads',
    cropName: record.cropType,
    remarks: record.status === 'Active' ? 'Active member' : 'Inactive member',
  }
})

export const mockNotifications = [
  {
    id: 1,
    message: '5 new registrations pending review',
    timestamp: '2 hours ago',
    type: 'info',
  },
  {
    id: 2,
    message: 'System maintenance scheduled for Sunday',
    timestamp: '1 day ago',
    type: 'warning',
  },
  {
    id: 3,
    message: 'Monthly report is ready for download',
    timestamp: '3 days ago',
    type: 'success',
  },
]
