-- ============================================================================
-- Olongapo Agriculture Registry Management System
-- Full Migration & Schema Initialization Script
-- ============================================================================

-- Enable required extensions
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. RECORDS TABLE (Farmer & Fisherfolk Registry)
-- ----------------------------------------------------------------------------
create table if not exists public.records (
  id bigint generated by default as identity primary key,
  name text,
  type text,
  barangay text,
  contact_number text,
  crop_type text,
  years_experience integer,
  created_at timestamptz not null default now(),
  status text,
  last_name text,
  first_name text,
  middle_name text,
  ext_name text,
  birthdate date,
  age integer,
  gender text,
  civil_status text,
  designation text,
  una_kard text,
  imc text,
  u_mobile_account text,
  lgu_code_no text,
  ffrs_system_generated_no text,
  ffrs_date_encoded date,
  fishr_no text,
  contact_no text,
  association text,
  family_members integer,
  organic text,
  four_ps_member text,
  ips_member text,
  pwd_member text,
  senior_citizen text,
  solo_parent text,
  severely_stunted_children integer,
  mother_maiden_name text,
  household_head text,
  household_head_specify text,
  type_of_id text,
  id_no text,
  farmer_fisherfolk_both text,
  farm_type text,
  crop_area_or_heads text,
  crop_name text,
  remarks text
);

-- Ensure specific columns exist for backward/forward compatibility
alter table public.records add column if not exists pwd_member text;
alter table public.records add column if not exists senior_citizen text;
alter table public.records add column if not exists solo_parent text;

-- ----------------------------------------------------------------------------
-- 2. NOTIFICATIONS TABLE (System logs & Alerts)
-- ----------------------------------------------------------------------------
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  message text not null,
  type text not null,
  created_at timestamptz not null default now(),
  display_timestamp text
);

-- ----------------------------------------------------------------------------
-- 3. USER PROFILES TABLE (Authentication & Metadata)
-- ----------------------------------------------------------------------------
create table if not exists public.user_profiles (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  full_name text,
  role text, -- e.g., 'farmer', 'officer', 'admin', 'fisherfolk'
  phone text,
  address text,
  municipality text,
  barangay text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 4. EVENTS TABLE (Department events & Activities)
-- ----------------------------------------------------------------------------
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null, -- formatted text (e.g. 'February 10, 2026') or ISO string
  time text not null, -- formatted time range (e.g. '9:00 AM – 3:00 PM')
  venue text not null,
  audience text not null,
  description text not null,
  status text not null default 'upcoming',
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 5. ATTENDANCE TABLE (Tracks event attendance via QR scans)
-- ----------------------------------------------------------------------------
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  record_id bigint not null references public.records(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (event_id, record_id)
);

-- ----------------------------------------------------------------------------
-- 6. VIEWS (Analytics & Summary Metrics)
-- ----------------------------------------------------------------------------
create or replace view public.analytics_overview as
select
  count(*)::integer as total_registered,
  count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'farmer')::integer as total_farmers,
  count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'fisherfolk')::integer as total_fisherfolks,
  count(*) filter (where lower(coalesce(status, '')) = 'active')::integer as active_members,
  count(*) filter (where lower(coalesce(status, '')) = 'inactive')::integer as inactive_members,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'farmer')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_farmers,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'fisherfolk')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_fisherfolks,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(status, '')) = 'active')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_active,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(status, '')) = 'inactive')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_inactive
from public.records;

-- ----------------------------------------------------------------------------
-- 7. FUNCTIONS & TRIGGERS (Automations & Helpers)
-- ----------------------------------------------------------------------------

-- Password verification function for user_profiles
create or replace function public.verify_password(password_input text, password_hash text)
returns boolean as $$
begin
  return password_hash = crypt(password_input, password_hash);
end;
$$ language plpgsql;

-- Trigger function to update updated_at timestamp automatically
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Bind updated_at trigger to user_profiles
drop trigger if exists update_user_profiles_updated_at on public.user_profiles;
create trigger update_user_profiles_updated_at
before update on public.user_profiles
for each row
execute function public.update_updated_at_column();

-- ----------------------------------------------------------------------------
-- 8. ROW LEVEL SECURITY (RLS) & ACCESS POLICIES
-- ----------------------------------------------------------------------------

-- Enable Row Level Security (RLS) on all tables
alter table public.records enable row level security;
alter table public.notifications enable row level security;
alter table public.user_profiles enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;

-- Policies for public.records (Allow full CRUD operations for public/anon client access)
drop policy if exists "Allow public read records" on public.records;
create policy "Allow public read records" on public.records for select using (true);

drop policy if exists "Allow public insert records" on public.records;
create policy "Allow public insert records" on public.records for insert with check (true);

drop policy if exists "Allow public update records" on public.records;
create policy "Allow public update records" on public.records for update using (true) with check (true);

drop policy if exists "Allow public delete records" on public.records;
create policy "Allow public delete records" on public.records for delete using (true);

-- Policies for public.notifications (Allow full CRUD operations)
drop policy if exists "Allow public read notifications" on public.notifications;
create policy "Allow public read notifications" on public.notifications for select using (true);

drop policy if exists "Allow public insert notifications" on public.notifications;
create policy "Allow public insert notifications" on public.notifications for insert with check (true);

drop policy if exists "Allow public update notifications" on public.notifications;
create policy "Allow public update notifications" on public.notifications for update using (true) with check (true);

drop policy if exists "Allow public delete notifications" on public.notifications;
create policy "Allow public delete notifications" on public.notifications for delete using (true);

-- Policies for public.user_profiles (Allow verification and self updates)
drop policy if exists "Allow public login verification" on public.user_profiles;
create policy "Allow public login verification" on public.user_profiles for select using (true);

drop policy if exists "Allow public insert user_profiles" on public.user_profiles;
create policy "Allow public insert user_profiles" on public.user_profiles for insert with check (true);

drop policy if exists "Allow public update user_profiles" on public.user_profiles;
create policy "Allow public update user_profiles" on public.user_profiles for update using (true) with check (true);

drop policy if exists "Allow public delete user_profiles" on public.user_profiles;
create policy "Allow public delete user_profiles" on public.user_profiles for delete using (true);

-- Policies for public.events (Allow full CRUD operations)
drop policy if exists "Allow public read events" on public.events;
create policy "Allow public read events" on public.events for select using (true);

drop policy if exists "Allow public insert events" on public.events;
create policy "Allow public insert events" on public.events for insert with check (true);

drop policy if exists "Allow public update events" on public.events;
create policy "Allow public update events" on public.events for update using (true) with check (true);

drop policy if exists "Allow public delete events" on public.events;
create policy "Allow public delete events" on public.events for delete using (true);

-- Policies for public.attendance (Allow full CRUD operations)
drop policy if exists "Allow public read attendance" on public.attendance;
create policy "Allow public read attendance" on public.attendance for select using (true);

drop policy if exists "Allow public insert attendance" on public.attendance;
create policy "Allow public insert attendance" on public.attendance for insert with check (true);

drop policy if exists "Allow public update attendance" on public.attendance;
create policy "Allow public update attendance" on public.attendance for update using (true) with check (true);

drop policy if exists "Allow public delete attendance" on public.attendance;
create policy "Allow public delete attendance" on public.attendance for delete using (true);

-- ----------------------------------------------------------------------------
-- 9. SEED DATA (Idempotent seed statements)
-- ----------------------------------------------------------------------------

-- Seed data for records (35 registered members)
with raw_records as (
  select * from (values
    (1, 'Juan Dela Cruz', 'Farmer', 'Barangay 1', '09171234567', 'Rice', 15, '2026-01-15', 'Active'),
    (2, 'Maria Santos', 'Fisherfolk', 'Barangay 2', '09171234568', 'Bangus', 10, '2026-01-16', 'Inactive'),
    (3, 'Pedro Reyes', 'Farmer', 'Barangay 3', '09171234569', 'Corn', 8, '2026-01-17', 'Active'),
    (4, 'Rosa Fernandez', 'Fisherfolk', 'Barangay 1', '09171234570', 'Tilapia', 12, '2026-01-18', 'Active'),
    (5, 'Antonio Morales', 'Farmer', 'Barangay 4', '09171234571', 'Vegetables', 6, '2026-01-19', 'Inactive'),
    (6, 'Luz Navarro', 'Fisherfolk', 'Barangay 5', '09171234572', 'Crab', 7, '2026-01-20', 'Active'),
    (7, 'Mario Cruz', 'Farmer', 'Barangay 2', '09171234573', 'Rice', 4, '2026-01-20', 'Active'),
    (8, 'Elena Ramos', 'Fisherfolk', 'Barangay 6', '09171234574', 'Shrimp', 5, '2026-01-21', 'Inactive'),
    (9, 'Ramon Diaz', 'Farmer', 'Barangay 7', '09171234575', 'Corn', 9, '2026-01-21', 'Active'),
    (10, 'Eva Bautista', 'Fisherfolk', 'Barangay 3', '09171234576', 'Bangus', 11, '2026-01-22', 'Active'),
    (11, 'Josefina Cruz', 'Farmer', 'Barangay 8', '09171234577', 'Vegetables', 2, '2026-01-22', 'Inactive'),
    (12, 'Noel Garcia', 'Farmer', 'Barangay 9', '09171234578', 'Rice', 14, '2026-01-23', 'Active'),
    (13, 'Carla Santos', 'Fisherfolk', 'Barangay 10', '09171234579', 'Tilapia', 3, '2026-01-23', 'Inactive'),
    (14, 'Vicente Lopez', 'Farmer', 'Barangay 11', '09171234580', 'Corn', 6, '2026-01-24', 'Active'),
    (15, 'Grace Ramos', 'Fisherfolk', 'Barangay 12', '09171234581', 'Shrimp', 8, '2026-01-24', 'Active'),
    (16, 'Leandro Pineda', 'Farmer', 'Barangay 1', '09171234582', 'Rice', 5, '2026-01-25', 'Inactive'),
    (17, 'Nina Alvarez', 'Fisherfolk', 'Barangay 4', '09171234583', 'Bangus', 10, '2026-01-25', 'Active'),
    (18, 'Arturo Mendoza', 'Farmer', 'Barangay 6', '09171234584', 'Vegetables', 7, '2026-01-26', 'Active'),
    (19, 'Belen Flores', 'Fisherfolk', 'Barangay 7', '09171234585', 'Tilapia', 4, '2026-01-26', 'Inactive'),
    (20, 'Oscar Reyes', 'Farmer', 'Barangay 8', '09171234586', 'Corn', 12, '2026-01-27', 'Active'),
    (21, 'Pia Gutierrez', 'Fisherfolk', 'Barangay 9', '09171234587', 'Crab', 6, '2026-01-27', 'Active'),
    (22, 'Rolando Santos', 'Farmer', 'Barangay 10', '09171234588', 'Rice', 9, '2026-01-28', 'Inactive'),
    (23, 'Sandra Dizon', 'Fisherfolk', 'Barangay 11', '09171234589', 'Shrimp', 3, '2026-01-28', 'Active'),
    (24, 'Tomas Aquino', 'Farmer', 'Barangay 12', '09171234590', 'Vegetables', 1, '2026-01-29', 'Inactive'),
    (25, 'Ursula Navarro', 'Fisherfolk', 'Barangay 5', '09171234591', 'Bangus', 11, '2026-01-29', 'Active'),
    (26, 'Waldo Castillo', 'Farmer', 'Barangay 2', '09171234592', 'Corn', 13, '2026-01-30', 'Active'),
    (27, 'Yolanda Cruz', 'Fisherfolk', 'Barangay 3', '09171234593', 'Tilapia', 5, '2026-01-30', 'Inactive'),
    (28, 'Zandro Villanueva', 'Farmer', 'Barangay 4', '09171234594', 'Rice', 3, '2026-01-31', 'Active'),
    (29, 'Alicia Lim', 'Fisherfolk', 'Barangay 6', '09171234595', 'Crab', 9, '2026-01-31', 'Active'),
    (30, 'Benito Ong', 'Farmer', 'Barangay 7', '09171234596', 'Vegetables', 4, '2026-02-01', 'Inactive'),
    (31, 'Carmen Uy', 'Fisherfolk', 'Barangay 8', '09171234597', 'Shrimp', 7, '2026-02-01', 'Active'),
    (32, 'Diego Tan', 'Farmer', 'Barangay 9', '09171234598', 'Corn', 6, '2026-02-02', 'Active'),
    (33, 'Estela Chua', 'Fisherfolk', 'Barangay 10', '09171234599', 'Tilapia', 2, '2026-02-02', 'Inactive'),
    (34, 'Federico Lao', 'Farmer', 'Barangay 11', '09171234600', 'Rice', 8, '2026-02-03', 'Active'),
    (35, 'Gloria Sy', 'Fisherfolk', 'Barangay 12', '09171234601', 'Bangus', 10, '2026-02-03', 'Inactive')
  ) as t(id, name, type, barangay, contact_number, crop_type, years_experience, created_at, status)
),
parts as (
  select
    *,
    string_to_array(name, ' ') as name_parts,
    row_number() over (order by id) - 1 as idx
  from raw_records
),
derived as (
  select
    id,
    name,
    type,
    barangay,
    contact_number,
    crop_type,
    years_experience,
    created_at::timestamptz,
    status,
    name_parts[1] as first_name,
    name_parts[array_length(name_parts, 1)] as last_name,
    case
      when array_length(name_parts, 1) > 2
        then array_to_string(name_parts[2:array_length(name_parts, 1) - 1], ' ')
      else ''
    end as middle_name,
    (18 + (id % 30)) as age,
    (2026 - (18 + (id % 30))) as birth_year,
    idx
  from parts
)
insert into public.records (
  id,
  name,
  type,
  barangay,
  contact_number,
  crop_type,
  years_experience,
  created_at,
  status,
  last_name,
  first_name,
  middle_name,
  ext_name,
  birthdate,
  age,
  gender,
  civil_status,
  designation,
  una_kard,
  imc,
  u_mobile_account,
  lgu_code_no,
  ffrs_system_generated_no,
  ffrs_date_encoded,
  fishr_no,
  contact_no,
  association,
  family_members,
  organic,
  four_ps_member,
  ips_member,
  pwd_member,
  senior_citizen,
  solo_parent,
  severely_stunted_children,
  mother_maiden_name,
  household_head,
  household_head_specify,
  type_of_id,
  id_no,
  farmer_fisherfolk_both,
  farm_type,
  crop_area_or_heads,
  crop_name,
  remarks
)
select
  id,
  name,
  type,
  barangay,
  contact_number,
  crop_type,
  years_experience,
  created_at,
  status,
  last_name,
  first_name,
  middle_name,
  '',
  make_date(birth_year, 1, 15),
  age,
  case when (idx % 2) = 0 then 'Male' else 'Female' end,
  case when (idx % 3) = 0 then 'Married' else 'Single' end,
  case when type = 'Farmer' then 'Farmer' else 'Fisherfolk' end,
  '',
  '',
  '',
  '',
  '',
  null,
  '',
  contact_number,
  case when (idx % 4) = 0 then 'Farmers Association' else 'Fisherfolk Union' end,
  (3 + (id % 5)),
  case when (idx % 2) = 0 then 'Yes' else 'No' end,
  case when (idx % 4) = 0 then 'Yes' else 'No' end,
  case when (idx % 5) = 0 then 'Yes' else 'No' end,
  case when (idx % 6) = 0 then 'Yes' else 'No' end,
  case when age >= 60 then 'Yes' else 'No' end,
  case when (idx % 7) = 0 then 'Yes' else 'No' end,
  case when (id % 3) = 0 then 1 else 0 end,
  case when (idx % 2) = 0 then 'Santos' else 'Reyes' end,
  case when (idx % 2) = 0 then 'Yes' else 'No' end,
  case when (idx % 2) = 0 then '' else 'Spouse' end,
  'National ID',
  'ID-' || lpad(id::text, 4, '0'),
  type,
  case when type = 'Farmer' then 'Crop' else 'Fishery' end,
  case when type = 'Farmer' then '2.5 ha' else '120 heads' end,
  crop_type,
  case when status = 'Active' then 'Active member' else 'Inactive member' end
from derived
on conflict (id) do nothing;

-- Seed data for notifications
insert into public.notifications (id, message, type, display_timestamp)
values
  (1, '5 new registrations pending review', 'info', '2 hours ago'),
  (2, 'System maintenance scheduled for Sunday', 'warning', '1 day ago'),
  (3, 'Monthly report is ready for download', 'success', '3 days ago')
on conflict (id) do nothing;

-- Seed data for user profiles (Credentials: email / password123)
insert into public.user_profiles (email, password_hash, full_name, role, phone, address, municipality, barangay)
values
  ('farmer@test.com', crypt('password123', gen_salt('bf')), 'Farmer User', 'farmer', '0917-111-2222', '123 Sprout Lane', 'Olongapo', 'Barangay 1'),
  ('officer@test.com', crypt('password123', gen_salt('bf')), 'Field Officer', 'officer', '0917-333-4444', '456 Registry Rd', 'Olongapo', 'Barangay 2'),
  ('admin@test.com', crypt('password123', gen_salt('bf')), 'System Admin', 'admin', '0917-555-6666', '789 Authority Ave', 'Olongapo', 'Barangay 3'),
  ('fisherman@test.com', crypt('password123', gen_salt('bf')), 'Fisherfolk User', 'fisherfolk', '0917-777-8888', '101 Bay View', 'Olongapo', 'Barangay 4')
on conflict (email) do nothing;

-- Seed data for events
insert into public.events (id, title, date, time, venue, audience, description, status)
values
  (1, 'Olongapo Coastal Resource Summit', 'February 10, 2026', '9:00 AM – 3:00 PM', 'Olongapo City Hall Plaza', 'Fisherfolks & Farmers', 'Updates on coastal management, community consultation, and programs supporting local fisherfolks and farmers.', 'completed'),
  (2, 'Integrated Farming & Aquaculture Fair', 'February 17, 2026', '8:00 AM – 5:00 PM', 'Barangay Barretto Covered Court', 'Fisherfolks & Farmers', 'Hands-on demos, seedling and fingerling distribution, and sign-ups for training opportunities.', 'completed'),
  (3, 'Disaster Preparedness & Livelihood Workshop', 'February 24, 2026', '1:00 PM – 4:30 PM', 'Olongapo Convention Center', 'Fisherfolks & Farmers', 'Community DRR training, emergency aid programs overview, and resilient livelihood planning.', 'completed'),
  (4, 'Citywide Registry Day: Fisherfolk & Farmer Enrollment', 'March 2, 2026', '8:00 AM – 4:00 PM', 'Olongapo City Agriculture Office', 'Open to all', 'On-site registration and updates for city programs and assistance. Bring valid ID.', 'upcoming')
on conflict (id) do nothing;

-- Seed data for event attendance
insert into public.attendance (event_id, record_id, created_at)
values
  (1, 1, '2026-02-10 10:15:00+08'),
  (1, 3, '2026-02-10 10:20:00+08'),
  (1, 4, '2026-02-10 10:22:00+08'),
  (2, 2, '2026-02-17 08:30:00+08'),
  (2, 4, '2026-02-17 08:45:00+08'),
  (3, 1, '2026-02-24 13:10:00+08')
on conflict (event_id, record_id) do nothing;
