-- ============================================================================
-- Olongapo Agriculture Registry Management System
-- Full Migration & Schema Initialization Script
-- ============================================================================

-- Enable required extensions
create extension if not exists pgcrypto;

-- Drop existing views and tables to ensure clean recreation
drop view if exists public.analytics_overview cascade;
drop table if exists public.attendance cascade;
drop table if exists public.events cascade;
drop table if exists public.user_profiles cascade;
drop table if exists public.notifications cascade;
drop table if exists public.records cascade;

-- ----------------------------------------------------------------------------
-- 1. RECORDS TABLE (Farmer & Fisherfolk Registry)
-- ----------------------------------------------------------------------------
create table if not exists public.records (
  id bigint generated by default as identity primary key,
  name text,
  type text,
  barangay text,
  contact_number text,
  crop_type text,
  years_experience integer,
  created_at timestamptz not null default now(),
  status text,
  last_name text,
  first_name text,
  middle_name text,
  ext_name text,
  birthdate date,
  age integer,
  gender text,
  civil_status text,
  designation text,
  una_kard text,
  imc text,
  u_mobile_account text,
  lgu_code_no text,
  ffrs_system_generated_no text,
  ffrs_date_encoded date,
  fishr_no text,
  contact_no text,
  association text,
  family_members integer,
  organic text,
  four_ps_member text,
  ips_member text,
  pwd_member text,
  senior_citizen text,
  solo_parent text,
  severely_stunted_children integer,
  mother_maiden_name text,
  household_head text,
  household_head_specify text,
  type_of_id text,
  id_no text,
  farmer_fisherfolk_both text,
  farm_type text,
  crop_area_or_heads text,
  crop_name text,
  remarks text
);

-- Ensure specific columns exist for backward/forward compatibility
alter table public.records add column if not exists pwd_member text;
alter table public.records add column if not exists senior_citizen text;
alter table public.records add column if not exists solo_parent text;

-- ----------------------------------------------------------------------------
-- 2. NOTIFICATIONS TABLE (System logs & Alerts)
-- ----------------------------------------------------------------------------
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  message text not null,
  type text not null,
  created_at timestamptz not null default now(),
  display_timestamp text
);

-- ----------------------------------------------------------------------------
-- 3. USER PROFILES TABLE (Authentication & Metadata)
-- ----------------------------------------------------------------------------
create table if not exists public.user_profiles (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  full_name text,
  role text, -- e.g., 'farmer', 'officer', 'admin', 'fisherfolk'
  phone text,
  address text,
  municipality text,
  barangay text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 4. EVENTS TABLE (Department events & Activities)
-- ----------------------------------------------------------------------------
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null, -- formatted text (e.g. 'February 10, 2026') or ISO string
  time text not null, -- formatted time range (e.g. '9:00 AM – 3:00 PM')
  venue text not null,
  audience text not null,
  description text not null,
  status text not null default 'upcoming',
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 5. ATTENDANCE TABLE (Tracks event attendance via QR scans)
-- ----------------------------------------------------------------------------
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  record_id bigint not null references public.records(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (event_id, record_id)
);

-- ----------------------------------------------------------------------------
-- 6. VIEWS (Analytics & Summary Metrics)
-- ----------------------------------------------------------------------------
create or replace view public.analytics_overview as
select
  count(*)::integer as total_registered,
  count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'farmer')::integer as total_farmers,
  count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'fisherfolk')::integer as total_fisherfolks,
  count(*) filter (where lower(coalesce(status, '')) = 'active')::integer as active_members,
  count(*) filter (where lower(coalesce(status, '')) = 'inactive')::integer as inactive_members,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'farmer')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_farmers,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(farmer_fisherfolk_both, type, '')) = 'fisherfolk')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_fisherfolks,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(status, '')) = 'active')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_active,
  case
    when count(*) = 0 then 0
    else round((count(*) filter (where lower(coalesce(status, '')) = 'inactive')::numeric / count(*)::numeric) * 100, 1)
  end as percentage_inactive
from public.records;

-- ----------------------------------------------------------------------------
-- 7. FUNCTIONS & TRIGGERS (Automations & Helpers)
-- ----------------------------------------------------------------------------

-- Password verification function for user_profiles
create or replace function public.verify_password(password_input text, password_hash text)
returns boolean as $$
begin
  return password_hash = crypt(password_input, password_hash);
end;
$$ language plpgsql;

-- Trigger function to update updated_at timestamp automatically
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Bind updated_at trigger to user_profiles
drop trigger if exists update_user_profiles_updated_at on public.user_profiles;
create trigger update_user_profiles_updated_at
before update on public.user_profiles
for each row
execute function public.update_updated_at_column();

-- ----------------------------------------------------------------------------
-- 8. ROW LEVEL SECURITY (RLS) & ACCESS POLICIES
-- ----------------------------------------------------------------------------

-- Enable Row Level Security (RLS) on all tables
alter table public.records enable row level security;
alter table public.notifications enable row level security;
alter table public.user_profiles enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;

-- Policies for public.records (Allow full CRUD operations for public/anon client access)
drop policy if exists "Allow public read records" on public.records;
create policy "Allow public read records" on public.records for select using (true);

drop policy if exists "Allow public insert records" on public.records;
create policy "Allow public insert records" on public.records for insert with check (true);

drop policy if exists "Allow public update records" on public.records;
create policy "Allow public update records" on public.records for update using (true) with check (true);

drop policy if exists "Allow public delete records" on public.records;
create policy "Allow public delete records" on public.records for delete using (true);

-- Policies for public.notifications (Allow full CRUD operations)
drop policy if exists "Allow public read notifications" on public.notifications;
create policy "Allow public read notifications" on public.notifications for select using (true);

drop policy if exists "Allow public insert notifications" on public.notifications;
create policy "Allow public insert notifications" on public.notifications for insert with check (true);

drop policy if exists "Allow public update notifications" on public.notifications;
create policy "Allow public update notifications" on public.notifications for update using (true) with check (true);

drop policy if exists "Allow public delete notifications" on public.notifications;
create policy "Allow public delete notifications" on public.notifications for delete using (true);

-- Policies for public.user_profiles (Allow verification and self updates)
drop policy if exists "Allow public login verification" on public.user_profiles;
create policy "Allow public login verification" on public.user_profiles for select using (true);

drop policy if exists "Allow public insert user_profiles" on public.user_profiles;
create policy "Allow public insert user_profiles" on public.user_profiles for insert with check (true);

drop policy if exists "Allow public update user_profiles" on public.user_profiles;
create policy "Allow public update user_profiles" on public.user_profiles for update using (true) with check (true);

drop policy if exists "Allow public delete user_profiles" on public.user_profiles;
create policy "Allow public delete user_profiles" on public.user_profiles for delete using (true);

-- Policies for public.events (Allow full CRUD operations)
drop policy if exists "Allow public read events" on public.events;
create policy "Allow public read events" on public.events for select using (true);

drop policy if exists "Allow public insert events" on public.events;
create policy "Allow public insert events" on public.events for insert with check (true);

drop policy if exists "Allow public update events" on public.events;
create policy "Allow public update events" on public.events for update using (true) with check (true);

drop policy if exists "Allow public delete events" on public.events;
create policy "Allow public delete events" on public.events for delete using (true);

-- Policies for public.attendance (Allow full CRUD operations)
drop policy if exists "Allow public read attendance" on public.attendance;
create policy "Allow public read attendance" on public.attendance for select using (true);

drop policy if exists "Allow public insert attendance" on public.attendance;
create policy "Allow public insert attendance" on public.attendance for insert with check (true);

drop policy if exists "Allow public update attendance" on public.attendance;
create policy "Allow public update attendance" on public.attendance for update using (true) with check (true);

drop policy if exists "Allow public delete attendance" on public.attendance;
create policy "Allow public delete attendance" on public.attendance for delete using (true);

-- ----------------------------------------------------------------------------
-- 9. SEED DATA (Idempotent seed statements)
-- ----------------------------------------------------------------------------

-- Seed data for user profiles (Credentials: email / password123)
insert into public.user_profiles (email, password_hash, full_name, role, phone, address, municipality, barangay)
values
  ('farmer@test.com', crypt('password123', gen_salt('bf')), 'Farmer User', 'farmer', '0917-111-2222', '123 Sprout Lane', 'Olongapo', 'Barangay 1'),
  ('officer@test.com', crypt('password123', gen_salt('bf')), 'Field Officer', 'officer', '0917-333-4444', '456 Registry Rd', 'Olongapo', 'Barangay 2'),
  ('admin@test.com', crypt('password123', gen_salt('bf')), 'System Admin', 'admin', '0917-555-6666', '789 Authority Ave', 'Olongapo', 'Barangay 3'),
  ('fisherman@test.com', crypt('password123', gen_salt('bf')), 'Fisherfolk User', 'fisherfolk', '0917-777-8888', '101 Bay View', 'Olongapo', 'Barangay 4')
on conflict (email) do nothing;
